services:
  app:
    container_name: ani_rec
    restart: unless-stopped
    image: nextjs-app
    build:
      context: ..
      dockerfile: deployment/next.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:     # only for development usage
      - ..:/app  # Mount project directory
